import { Component, OnInit, Optional, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { MatDialogRef, MatDialogModule } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { OccupationRequest } from '../../model/occupation';
import { OccupationService } from '../occupation.service';

@Component({
  selector: 'app-add',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatCardModule,
    MatDialogModule,
    MatIconModule
  ],
  templateUrl: './add.html',
  styleUrls: ['./add.css'],
})
export class AddOccupation implements OnInit {
  occupationForm: FormGroup;
  isDialog: boolean = false;
  isLoading = false;
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private occupationService: OccupationService,
    private cdr: ChangeDetectorRef,
    @Optional() private dialogRef: MatDialogRef<AddOccupation>
  ) {
    this.isDialog = !!this.dialogRef;
    this.occupationForm = this.fb.group({
      occCode: [{ value: '', disabled: true }], // Read-only, auto-generated
      occName: ['', [Validators.required, Validators.maxLength(100)]],
      description: ['', Validators.maxLength(500)]
    });
  }

  ngOnInit() {
    // occCode will be generated by the backend
    this.occupationForm.get('occCode')?.setValue('Auto-generated');
  }

  onSubmit() {
    if (this.occupationForm.invalid) {
      // Mark all fields as touched to show validation errors
      Object.keys(this.occupationForm.controls).forEach(key => {
        this.occupationForm.get(key)?.markAsTouched();
      });
      return;
    }

    // Format occupation name: trim, collapse spaces and title-case each word (Vietnamese locale)
    const rawName = (this.occupationForm.get('occName')?.value || '').toString();
    const formattedName = this.titleCase(rawName.trim().replace(/\s+/g, ' '));

    // Update form so user sees the formatted value
    this.occupationForm.get('occName')?.setValue(formattedName);

    const requestBody: OccupationRequest = {
      name: formattedName,
      description: this.occupationForm.get('description')?.value || ''
    };

    this.isLoading = true;
    this.errorMessage = '';

    this.occupationService.create(requestBody).subscribe({
      next: (response) => {
        console.log('Occupation created successfully:', response);

        const occupationData = response;

        // If opened as dialog, close with response data
        if (this.isDialog && this.dialogRef) {
          this.dialogRef.close({
            occCode: occupationData.occCode?.toString() || '',
            occName: occupationData.occName,
            description: occupationData.description
          });
        } else {
          // Reset form and show success
          this.occupationForm.reset();
          this.occupationForm.get('occCode')?.setValue('Auto-generated');
        }

        this.isLoading = false;
        this.cdr.detectChanges();
      },
      error: (error: any) => {
        console.error('Error creating occupation:', error);
        this.isLoading = false;

        // ApiClient returns normalized error with status and message
        // 401 errors are automatically redirected to login by ApiClient
        if (error.status === 0) {
          this.errorMessage = 'Không thể kết nối đến máy chủ. Vui lòng kiểm tra kết nối mạng.';
        } else if (error.status === 403) {
          this.errorMessage = 'Bạn không có quyền thực hiện thao tác này.';
        } else if (error.status === 400) {
          this.errorMessage = error.message || 'Dữ liệu không hợp lệ.';
        } else if (error.status === 409) {
          this.errorMessage = 'Nghề nghiệp này đã tồn tại.';
        } else if (error.status >= 500) {
          this.errorMessage = error.message || 'Lỗi máy chủ. Vui lòng thử lại sau.';
        } else {
          this.errorMessage = error.message || 'Đã xảy ra lỗi. Vui lòng thử lại.';
        }

        this.cdr.detectChanges();
      }
    });
  }

  private titleCase(input: string): string {
    if (!input) return input;

    // Split on whitespace, preserve single spaces between words
    return input.split(/\s+/).map(word => {
      // Handle hyphenated parts like "x-y"
      return word.split('-').map(part => {
        const lower = part.toLocaleLowerCase('vi-VN');
        const first = part.charAt(0) ? part.charAt(0).toLocaleUpperCase('vi-VN') : '';
        return first + lower.slice(1);
      }).join('-');
    }).join(' ');
  }

  formatOccName() {
    const raw = (this.occupationForm.get('occName')?.value || '').toString();
    const formatted = this.titleCase(raw.trim().replace(/\s+/g, ' '));
    this.occupationForm.get('occName')?.setValue(formatted);
  }

  onCancel() {
    if (this.isDialog && this.dialogRef) {
      this.dialogRef.close();
    } else {
      this.occupationForm.reset();
      this.occupationForm.get('occCode')?.setValue('Auto-generated');
    }
  }
}
